In [1]:
import pandas as pd

import numpy as np 
import seaborn as sns 
import glob
import os

Upload all geo file , which can be downloaded form (put name of geographic website), upload all the file in github repo and then copy and paste the link below. 
Important note: please do not change the file name of excel

In [2]:
!git clone https://github.com/hanihaider1/why-my-city-smell-bad-/

fatal: destination path 'why-my-city-smell-bad-' already exists and is not an empty directory.

In [3]:
path = './why-my-city-smell-bad-/'
lst = os.listdir(path)

In [5]:
df= pd.DataFrame()
df_new= pd.DataFrame()

for i in lst:
  url = path+i
  if i[-4:]==".csv":
    if df.empty==True :
      df = pd.read_csv(url)
      df["Pod Name"] = i[:5]
    else:
      df_new= pd.read_csv(url)
      df_new["Pod Name"]= i[:5]
      df= df.append(df_new)

                     Time  Temp Avg  Temp Low  ...  lvl2  lvl3  Pod Name
0     2020-11-25 10:00:00     72.51      72.5  ...   NaN   NaN     SMRO7
1     2020-11-25 11:00:00     72.67      72.5  ...   NaN   NaN     SMRO7
2     2021-01-29 13:00:00     19.58      19.5  ...   NaN   NaN     SMRO7
3     2021-01-29 14:00:00     20.13      18.8  ...   NaN   NaN     SMRO7
4     2021-01-29 15:00:00     23.36      22.0  ...   NaN   NaN     SMRO7
...                   ...       ...       ...  ...   ...   ...       ...
7755  2021-07-23 20:00:00     63.59      63.1  ...   NaN   NaN     SMRO3
7756  2021-07-23 21:00:00     62.78      62.2  ...   NaN   NaN     SMRO3
7757  2021-07-23 22:00:00     61.78      61.5  ...   NaN   NaN     SMRO3
7758  2021-07-23 23:00:00     61.04      60.5  ...   NaN   NaN     SMRO3
7759  2021-07-24 00:00:00     59.96      59.6  ...   NaN   NaN     SMRO3

[23527 rows x 38 columns]